import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';

export default tseslint.config(
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    // Make an out-of-range TypeScript fail the lint gate. typescript-eslint
    // 8.70.0 supports `>=4.8.4 <6.1.0`; its default for anything outside that
    // is 'warn', which is a console.log guarded by `process.stdout.isTTY` —
    // so in CI it prints nothing and exits 0, and a TypeScript 6.1 or 7 bump
    // would land completely green. 'error' makes the parser throw instead,
    // which is the only thing that actually defends the ceiling. See #107.
    languageOptions: {
      parserOptions: { onUnsupportedTypeScriptVersion: 'error' },
    },
  },
  // eslint-plugin-react-hooks v7 ships the classic hook rules plus the React
  // Compiler rule set. We take the whole preset (see the override below for the
  // one exception) so hook bugs fail CI rather than shipping.
  reactHooks.configs.flat.recommended,
  {
    // The Next.js rules without eslint-config-next: that package's 15.x line
    // pins `eslint: ^7 || ^8 || ^9` and this repo is on ESLint 10, while its
    // 16.x line targets Next 16. The underlying plugin has no peer range, so we
    // register it directly and take both of its rule sets.
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/ban-ts-comment': 'error',
      // The preset ships this at 'warn'. `pnpm run lint` runs with
      // --max-warnings=0 so that already fails the build; say so explicitly.
      'react-hooks/exhaustive-deps': 'error',
      // Off deliberately, not because it is noise. It flags 12 pre-existing
      // effects that call setState synchronously. Each one needs its own
      // behaviour-preserving restructure, there are no component tests behind
      // them yet (issue #63), and doing that here would bury the hook-rule
      // change it is bundled with. Tracked in issue #131.
      'react-hooks/set-state-in-effect': 'off',
      // The preset also ships these two at 'warn'; raised for the same reason.
      'react-hooks/incompatible-library': 'error',
      'react-hooks/unsupported-syntax': 'error',
    },
  },
  {
    // next-env.d.ts is generated by `next build` and says not to edit it. Next
    // 15 adds a third triple-slash reference to it, which
    // @typescript-eslint/triple-slash-reference rejects — eslint-config-next
    // ignores the file for exactly this reason, and this config uses
    // @next/eslint-plugin-next directly rather than eslint-config-next, so it
    // has to repeat the ignore.
    ignores: ['.next/**', 'dist/**', 'node_modules/**', '**/next-env.d.ts'],
  }
);
