import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/ban-ts-comment': 'error',
    },
  },
  {
    // next-env.d.ts is generated by `next build` and says not to edit it. Next
    // 15 adds a third triple-slash reference to it, which
    // @typescript-eslint/triple-slash-reference rejects — eslint-config-next
    // ignores the file for exactly this reason, and this config deliberately
    // does not use eslint-config-next.
    ignores: ['.next/**', 'dist/**', 'node_modules/**', '**/next-env.d.ts'],
  }
);
